{% set name = "nncf" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1877192b44d36055f39fe212ca0abf04416bac1ff81be1b6cda0fbe82c12ac5

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --install-option=release

requirements:
  host:
    - pip==22.2
    - python >=3.7
    - python-build
    - setuptools >=59.5.0
    - wheel
  run:
    - jsonschema >=3.2.0
    - jstyleson >=0.0.2
    - natsort >=7.1.0
    - networkx >=2.6, <=2.8.2
    - ninja >=1.10.0.post2, <1.11
    - numpy >1.19.2, <1.24
    - openvino-telemetry >=2023.1.0
    - packaging >=20.0
    - pandas >=1.1.5, <2.1
    - pip
    - pymoo ==0.5.0
    - psutil
    - pydot >=1.4.1
    - pyparsing <3.0
    - python >=3.7
    - scikit-learn >=0.24.0
    - scipy >=1.3.2, <1.11
    - texttable >=1.6.3
    - tqdm >=4.54.1

test:
  imports:
    - nncf
    - nncf.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openvinotoolkit/nncf
  summary: Neural Networks Compression Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - vshampor
