{% set name = "nncf" %}
{% set version = "2.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 645cb21a3a6a252b95770f4565f5cd83cd8bc465287f92a798731edc73304414

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --install-option=--release

requirements:
  host:
    - pip ==22.2
    - python >=3.8, <3.12
    - python-build
    - setuptools >=59.5.0
    - wheel
  run:
    - jsonschema >=3.2.0
    - jstyleson >=0.0.2
    - natsort >=7.1.0
    - networkx >=2.6, <=2.8.2
    - ninja >=1.10.0.post2, <1.11
    - numpy >=1.19.1, <1.27
    - openvino-telemetry >=2023.2.0
    - packaging >=20.0
    - pandas >=1.1.5, <2.1
    - pymoo >=0.6.0.1
    - psutil
    - pydot >=1.4.1
    - pyparsing <3.0
    - rich >=13.5.2
    - python >=3.8
    - scikit-learn >=0.24.0
    - scipy >=1.3.2
    - texttable >=1.6.3
    - tqdm >=4.54.1

test:
  imports:
    - nncf
    - nncf.api
#  commands:
#    - pip check  # won't work because conda's version of ninja does not get registered in pip - https://github.com/mesonbuild/meson-python/issues/60, https://github.com/pypa/pip/issues/11157
  requires:
    - pip

about:
  home: https://github.com/openvinotoolkit/nncf
  summary: Neural Networks Compression Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - vshampor
